export const SET_KEYBOARD_ACTIVE = 'SET_KEYBOARD_ACTIVE';
export const SET_KEYBOARD_HEIGHT = 'SET_KEYBOARD_HEIGHT';

export const KEYBOARD_OPEN = 'KEYBOARD_OPEN';
export const KEYBOARD_CLOSE = 'KEYBOARD_CLOSE';